package Project.Commons;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLIENT_ID, RESET_USER_LIST,
    SYNC_CLIENT, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
    READY,SWITCH_ROOM,START_ROUND, ANSWER, END_ROUND, SCORE
}